#!/bin/bash
set -euo pipefail

# Copyright (c) 2025 Liam Mercier
#
# This file is part of SilentTanks.
#
# SilentTanks is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License Version 3.0
# as published by the Free Software Foundation.
#
# SilentTanks is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License v3.0
# for more details.
#
# You should have received a copy of the GNU Affero General Public License v3.0
# along with SilentTanks. If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>

ASSET_PATH="/var/lib/silent-tanks"
export SILENTTANKS_ASSET_DIR="$ASSET_PATH"

PGPASS_FILE="/var/lib/silent-tanks/.pgpass"
export PGPASSFILE="$PGPASS_FILE"

REAL="/usr/lib/silent-tanks/SilentTanks-Server"

exec sudo -u silent-tanks env \
    SILENTTANKS_ASSET_DIR="$SILENTTANKS_ASSET_DIR" \
    PGPASSFILE="$PGPASSFILE" \
    "$REAL" "$@"
